#!/bin/sh

QA_A="http://www.oliver-saal.de/software/afutrainer/download/DL%20Technik%20Klasse%20A%202007.aqz"
QA_E="http://www.oliver-saal.de/software/afutrainer/download/DL%20Technik%20Klasse%20E%202007.aqz"
QA_AE="http://www.oliver-saal.de/software/afutrainer/download/DL%20Betriebstechnik%20und%20Vorschriften%202007.aqz"


DJ4UF_E="
http://www.dj4uf.de/lehrg/vorwort.htm
http://www.dj4uf.de/lehrg/hinweise.html
http://www.dj4uf.de/lehrg/e01/e01.html
http://www.dj4uf.de/lehrg/e02/e02.html
http://www.dj4uf.de/lehrg/e03/e03.html
http://www.dj4uf.de/lehrg/e04/e04.html
http://www.dj4uf.de/lehrg/e05/e05.html
http://www.dj4uf.de/lehrg/e06/e06.html
http://www.dj4uf.de/lehrg/e07/e07.html
http://www.dj4uf.de/lehrg/e08/e08.html
http://www.dj4uf.de/lehrg/e09/e09.html
http://www.dj4uf.de/lehrg/e10/e10.html
http://www.dj4uf.de/lehrg/e11/e11.html
http://www.dj4uf.de/lehrg/e12/e12.html
http://www.dj4uf.de/lehrg/e13/e13.html
http://www.dj4uf.de/lehrg/e14/e14.html
http://www.dj4uf.de/lehrg/e15/e15.html
http://www.dj4uf.de/lehrg/e16/e16.html
http://www.dj4uf.de/lehrg/e17/e17.html
http://www.dj4uf.de/lehrg/e18/e18.html
http://www.dj4uf.de/lehrg/bv06/bv06.htm
http://www.dj4uf.de/download/Formelsammlung_KlasseE.pdf
"

DJ4UF_AE="
http://www.dj4uf.de/lehrg/bv01/bv01.htm
http://www.dj4uf.de/lehrg/bv02/bv02.htm
http://www.dj4uf.de/lehrg/bv03/bv03.htm
http://www.dj4uf.de/lehrg/bv04/bv04.htm
http://www.dj4uf.de/lehrg/bv05/bv05.htm
http://www.dj4uf.de/lehrg/bv06/bv06.htm
http://www.dj4uf.de/lehrg/bv07/bv07.htm
http://www.dj4uf.de/lehrg/bv08/bv08.htm
http://www.dj4uf.de/lehrg/bv09/bv09.htm
http://www.dj4uf.de/lehrg/bv10/bv10.htm
http://www.dj4uf.de/lehrg/bv11/bv11.htm
http://www.dj4uf.de/lehrg/bv12/bv12.htm
http://www.dj4uf.de/lehrg/bv13/bv13.htm
http://www.dj4uf.de/lehrg/bv14/bv14.htm
http://www.dj4uf.de/lehrg/bv15/bv15.htm
http://www.dj4uf.de/lehrg/bv16/bv16.htm
http://www.dj4uf.de/lehrg/bv17/bv17.htm
"

DJ4UF_A="
http://www.dj4uf.de/lehrg/a01/a01.html
http://www.dj4uf.de/lehrg/a02/a02.html
http://www.dj4uf.de/lehrg/a03/a03.html
http://www.dj4uf.de/lehrg/a04/a04.html
http://www.dj4uf.de/lehrg/a05/a05.html
http://www.dj4uf.de/lehrg/a06/a06.html
http://www.dj4uf.de/lehrg/a07/a07.html
http://www.dj4uf.de/lehrg/a08/a08.html
http://www.dj4uf.de/lehrg/a09/a09.html
http://www.dj4uf.de/lehrg/a10/a10.html
http://www.dj4uf.de/lehrg/a11/a11.html
http://www.dj4uf.de/lehrg/a12/a12.html
http://www.dj4uf.de/lehrg/a13/a13.html
http://www.dj4uf.de/lehrg/a14/a14.html
http://www.dj4uf.de/lehrg/a15/a15.html
http://www.dj4uf.de/lehrg/a16/a16.html
http://www.dj4uf.de/lehrg/a17/a17.html
http://www.dj4uf.de/lehrg/a18/a18.html
http://www.dj4uf.de/lehrg/a19/a19.html
http://www.dj4uf.de/lehrg/tipps.html
http://www.dj4uf.de/lehrg/tipps.html
"

BNETZA_A="http://www.bundesnetzagentur.de/media/archive/7637.pdf"
BNETZA_AE="http://www.bundesnetzagentur.de/media/archive/7830.pdf"
BNETZA_E="http://www.bundesnetzagentur.de/media/archive/9014.pdf"


dd () {
   d=$1
   shift
   urls=$@

   [[ -e $d ]]  || mkdir $d
   cd $d

   #wget -p -k $urls
   cd www.oliver-saal.de/software/afutrainer/download
   unzip -o *aqz 
   rm *aqz
   cd ../../../../

   cd ..

   tar cvjf Data_$d.tar.bz2 $d
}
   
dd TechnikA $BNETZA_A $DJ4UF_A $QA_A
dd TechnikE $BNETZA_E $DJ4UF_E $QA_E
dd BetriebAE $BNETZA_AE $DJ4UF_AE $QA_AE

